# -*- coding: utf-8 -*-
"""2026赛季分类表（225条，逐判例复核：基于评议组认定原文）
格式: seq -> (类别, 标签列表, 裁判判定, VAR判定)
判定口径与 CLS_2025 一致:
  - 申诉问题被支持但另漏判黄/红牌 → wrong（纪律处罚漏判计入）
  - "评议组对X不予认定"(证据不足) → pending；"支持裁判员决定"(证据不足为理由) → correct
  - 仅VAR程序错误、裁判员判罚正确 → correct + var_verdict=wrong
"""

CLS_2026 = {
    # 期01（标题2例）
    1: ("handball", ["点球", "漏判", "手臂不自然扩大", "VAR未介入错误"], "wrong", "wrong"),
    2: ("penalty_area", ["点球", "绊摔", "假摔不成立"], "wrong", "none"),
    # 期02（标题4例）
    3: ("penalty_area", ["点球", "犯规地点", "VAR未介入错误"], "wrong", "wrong"),
    4: ("goal_decision", ["冲撞守门员", "进球无效", "延迟鸣哨"], "wrong", "none"),
    5: ("dogso", ["守门员", "手球", "SPA", "黄牌", "DOGSO不成立"], "correct", "none"),
    6: ("sfp_vc", ["挥臂", "漏判", "证据不足"], "wrong", "none"),
    7: ("penalty_area", ["点球", "拉扯"], "wrong", "none"),
    # 期03（标题7例；本合集9例——含2例申诉问题正确但漏判黄牌的纪律处罚漏判）
    8: ("handball", ["手球", "进球无效"], "correct", "correct"),
    9: ("goal_decision", ["推搡", "进球无效"], "correct", "none"),
    10: ("sfp_vc", ["黄牌", "铲球", "红牌不成立"], "correct", "correct"),
    11: ("sfp_vc", ["黄牌", "踩踏", "红牌不成立"], "wrong", "correct"),
    12: ("handball", ["证据不足", "进球有效"], "correct", "correct"),
    13: ("penalty_area", ["轻微接触"], "correct", "correct"),
    14: ("offside", ["越位位置", "对方主动处理球", "VAR介入错误"], "correct", "wrong"),
    15: ("handball", ["点球", "手臂不自然扩大", "VAR未介入错误"], "wrong", "wrong"),
    16: ("penalty_area", ["点球", "绊摔"], "wrong", "none"),
    17: ("handball", ["点球", "手臂不自然扩大"], "wrong", "none"),
    18: ("penalty_area", ["主动倒地"], "correct", "none"),
    19: ("handball", ["点球", "手臂不自然扩大"], "wrong", "none"),
    20: ("sfp_vc", ["红牌", "严重犯规", "铲球"], "wrong", "none"),
    21: ("handball", ["DOGSO不成立", "证据不足"], "pending", "none"),
    22: ("sfp_vc", ["黄牌", "凌空踢", "红牌不成立"], "wrong", "none"),
    23: ("penalty_area", ["误判", "主动接触"], "wrong", "none"),
    24: ("penalty_area", ["点球", "绊摔"], "wrong", "none"),
    25: ("sfp_vc", ["黄牌", "铲球", "红牌不成立"], "correct", "none"),
    26: ("penalty_area", ["点球", "铲球"], "correct", "none"),
    # 期04（标题5例）
    27: ("penalty_area", ["点球", "铲球", "VAR回看错误"], "wrong", "correct"),
    28: ("handball", ["自然位置", "意外手球"], "correct", "correct"),
    29: ("offside", ["越位位置", "受限触球"], "correct", "correct"),
    30: ("handball", ["自然位置", "反弹"], "correct", "correct"),
    31: ("penalty_area", ["轻微接触"], "correct", "correct"),
    32: ("handball", ["证据不足"], "pending", "none"),
    33: ("penalty_area", ["守门员", "坠球"], "correct", "none"),
    34: ("penalty_area", ["争抢位置"], "correct", "none"),
    35: ("sfp_vc", ["黄牌", "踩踏", "暴力行为不成立"], "correct", "none"),
    36: ("handball", ["证据不足"], "pending", "none"),
    37: ("penalty_area", ["点球重罚", "提前进入"], "wrong", "none"),
    38: ("penalty_area", ["证据不足"], "pending", "none"),
    39: ("offside", ["越位误判", "进球有效"], "wrong", "none"),
    40: ("handball", ["手球", "犯规地点", "直接任意球"], "wrong", "none"),
    41: ("penalty_area", ["守门员"], "correct", "none"),
    42: ("offside", ["越位误判", "暴力行为不成立"], "wrong", "none"),
    43: ("offside", ["越位位置", "干扰对方", "证据不足"], "correct", "none"),
    44: ("sfp_vc", ["红牌", "严重犯规", "铲球"], "wrong", "none"),
    45: ("penalty_area", ["误判", "先触球"], "wrong", "none"),
    46: ("sfp_vc", ["黄牌", "铲球", "红牌不成立"], "correct", "none"),
    # 期05（标题3例；本合集6例——含漏判红/黄牌与漏判越位各1）
    47: ("sfp_vc", ["红牌", "严重犯规", "踩踏", "VAR未介入错误"], "wrong", "wrong"),
    48: ("penalty_area", ["争抢球"], "correct", "correct"),
    49: ("penalty_area", ["轻微接触"], "correct", "correct"),
    50: ("goal_decision", ["争抢高球", "进球有效"], "correct", "correct"),
    51: ("sfp_vc", ["黄牌", "蹬踏", "红牌不成立"], "wrong", "correct"),
    52: ("handball", ["自然位置", "球向手臂移动"], "correct", "correct"),
    53: ("sfp_vc", ["黄牌", "红牌不成立"], "correct", "correct"),
    54: ("penalty_area", ["争抢球"], "correct", "correct"),
    55: ("goal_decision", ["争抢位置", "进球有效"], "correct", "correct"),
    56: ("handball", ["点球", "手臂不自然扩大"], "correct", "none"),
    57: ("freekick_foul", ["绊摔", "SPA", "黄牌", "罚球区外"], "wrong", "none"),
    58: ("penalty_area", ["点球", "拉扯", "黄牌"], "wrong", "none"),
    59: ("offside", ["越位位置", "干扰对方", "进球有效"], "wrong", "none"),
    60: ("sfp_vc", ["挥臂", "暴力行为不成立"], "correct", "none"),
    61: ("sfp_vc", ["红牌", "暴力行为", "无球状态"], "correct", "none"),
    # 期06（标题6例；本合集7例——含1例漏判黄牌）
    62: ("penalty_area", ["点球", "黄牌", "VAR未介入错误"], "wrong", "wrong"),
    63: ("penalty_area", ["正常接触"], "correct", "correct"),
    64: ("sfp_vc", ["黄牌", "挥臂", "红牌不成立"], "correct", "correct"),
    65: ("penalty_area", ["守门员", "误判"], "wrong", "none"),
    66: ("penalty_area", ["轻微接触"], "correct", "none"),
    67: ("sfp_vc", ["黄牌", "红牌不成立"], "wrong", "none"),
    68: ("penalty_area", ["先触球", "误判"], "wrong", "none"),
    69: ("offside", ["越位误判"], "wrong", "none"),
    70: ("handball", ["手球", "进球无效"], "correct", "none"),
    71: ("sfp_vc", ["黄牌", "非体育行为", "红牌不成立"], "wrong", "none"),
    72: ("goal_decision", ["冲撞守门员", "证据不足", "进球无效"], "correct", "none"),
    73: ("penalty_area", ["点球", "拉扯"], "wrong", "none"),
    # 期07（标题8例；本合集11例——含3例漏判黄牌/越位类）
    74: ("sfp_vc", ["红牌", "严重犯规", "踩踏"], "correct", "correct"),
    75: ("penalty_area", ["主动倒地", "误判", "VAR回看错误"], "wrong", "correct"),
    76: ("sfp_vc", ["黄牌", "非体育行为", "红牌不成立", "越位误判"], "wrong", "none"),
    77: ("handball", ["自然位置", "近距离变线", "进球有效", "VAR介入错误"], "wrong", "wrong"),
    78: ("penalty_area", ["守门员", "冲撞", "点球"], "correct", "correct"),
    79: ("handball", ["手球", "手臂不自然扩大", "进球无效"], "wrong", "none"),
    80: ("freekick_foul", ["拉扯", "SPA", "黄牌"], "wrong", "none"),
    81: ("goal_decision", ["犯规在先", "进球无效"], "wrong", "none"),
    82: ("sfp_vc", ["红牌", "暴力行为", "快发任意球"], "correct", "none"),
    83: ("penalty_area", ["正常接触"], "correct", "none"),
    84: ("penalty_area", ["点球", "绊摔"], "wrong", "none"),
    85: ("sfp_vc", ["黄牌", "非体育行为", "证据不足", "红牌不成立"], "wrong", "none"),
    86: ("handball", ["证据不足"], "pending", "none"),
    87: ("sfp_vc", ["红牌", "严重犯规", "铲球"], "wrong", "none"),
    88: ("penalty_area", ["点球", "铲球"], "wrong", "none"),
    89: ("offside", ["越位位置", "干扰比赛", "进球有效"], "wrong", "none"),
    # 期08（标题5例；本合集6例——含1例漏判黄牌）
    90: ("penalty_area", ["自然位置", "正常接触"], "correct", "correct"),
    91: ("handball", ["点球", "手向球移动", "VAR未介入错误"], "wrong", "wrong"),
    92: ("sfp_vc", ["黄牌", "铲球", "红牌不成立"], "correct", "correct"),
    93: ("sfp_vc", ["黄牌", "手臂阻挡", "红牌不成立"], "wrong", "correct"),
    94: ("sfp_vc", ["黄牌", "踩踏", "红牌不成立"], "correct", "correct"),
    95: ("handball", ["自然位置", "VAR介入错误"], "correct", "wrong"),
    96: ("goal_decision", ["冲撞", "乌龙球", "进球无效"], "correct", "correct"),
    97: ("penalty_area", ["点球", "踢人", "VAR未介入错误"], "wrong", "wrong"),
    98: ("penalty_area", ["轻微接触", "主动倒地"], "correct", "correct"),
    99: ("penalty_area", ["假摔", "误判", "VAR回看错误"], "wrong", "correct"),
    100: ("handball", ["自然位置", "反弹"], "correct", "none"),
    101: ("handball", ["证据不足"], "pending", "none"),
    102: ("handball", ["点球", "手向球移动"], "wrong", "none"),
    103: ("penalty_area", ["点球", "绊摔"], "wrong", "none"),
    # 期09（标题3例；本合集5例——官方口径含VAR正确维持与支持性结论差异）
    104: ("penalty_area", ["正常接触", "VAR介入错误"], "correct", "wrong"),
    105: ("offside", ["VAR划线", "进球有效"], "correct", "correct"),
    106: ("goal_decision", ["争抢高球", "进球有效"], "correct", "correct"),
    107: ("handball", ["意外手球", "自然位置"], "correct", "none"),
    108: ("penalty_area", ["假摔", "黄牌"], "correct", "none"),
    109: ("penalty_area", ["点球", "冲撞"], "wrong", "none"),
    110: ("penalty_area", ["争抢球"], "correct", "none"),
    111: ("sfp_vc", ["黄牌", "红牌不成立"], "correct", "none"),
    112: ("sfp_vc", ["红牌", "暴力行为", "非体育行为"], "wrong", "none"),
    113: ("dogso", ["红牌", "DOGSO"], "correct", "none"),
    114: ("handball", ["手球", "进球无效"], "correct", "none"),
    115: ("penalty_area", ["误判", "正常接触"], "wrong", "none"),
    116: ("penalty_area", ["轻微接触"], "correct", "none"),
    117: ("offside", ["证据不足", "越位位置"], "correct", "none"),
    # 期10（标题5例；本合集6例——含1例多余黄牌）
    118: ("goal_decision", ["冲撞守门员", "进球有效", "误判"], "wrong", "none"),
    119: ("penalty_area", ["轻微接触", "主动倒地"], "correct", "none"),
    120: ("penalty_area", ["正常接触"], "correct", "none"),
    121: ("handball", ["点球", "手臂不自然扩大"], "wrong", "none"),
    122: ("handball", ["证据不足"], "correct", "none"),
    123: ("goal_decision", ["争抢高球", "误判", "提前鸣哨"], "wrong", "none"),
    124: ("handball", ["守门员", "误判", "红牌"], "wrong", "none"),
    125: ("sfp_vc", ["黄牌", "拉扯", "SPA不成立"], "wrong", "none"),
    126: ("sfp_vc", ["黄牌", "手臂", "红牌不成立"], "wrong", "none"),
    # 期11（标题口径：本轮中超无错漏判；本合集5例均为中甲/中乙/女超）
    127: ("offside", ["越位位置", "干扰对方", "VAR回看"], "correct", "none"),
    128: ("penalty_area", ["犯规地点", "VAR介入正确"], "correct", "correct"),
    129: ("handball", ["意外手球", "自然位置"], "correct", "correct"),
    130: ("penalty_area", ["点球", "踢人"], "correct", "correct"),
    131: ("penalty_area", ["点球", "犯规地点"], "wrong", "none"),
    132: ("offside", ["越位位置", "干扰比赛", "进球无效"], "wrong", "none"),
    133: ("sfp_vc", ["红牌", "暴力行为", "黄牌", "延误恢复"], "wrong", "none"),
    134: ("sfp_vc", ["红牌", "踩踏", "暴力行为"], "wrong", "none"),
    135: ("handball", ["自然位置"], "correct", "none"),
    136: ("penalty_area", ["点球", "冲撞"], "wrong", "none"),
    137: ("penalty_area", ["铲球", "误判"], "wrong", "none"),
    # 期12（标题1例）
    138: ("dogso", ["红牌", "DOGSO", "VAR介入正确"], "correct", "correct"),
    139: ("offside", ["越位位置", "干扰对方", "VAR介入错误"], "correct", "wrong"),
    140: ("offside", ["证据不足"], "correct", "none"),
    141: ("penalty_area", ["证据不足"], "correct", "none"),
    142: ("handball", ["自然位置", "误判"], "wrong", "none"),
    143: ("penalty_area", ["证据不足"], "correct", "none"),
    144: ("penalty_area", ["证据不足"], "correct", "none"),
    145: ("penalty_area", ["轻微接触"], "correct", "none"),
    146: ("penalty_area", ["拉扯", "轻微接触"], "correct", "none"),
    # 期13（标题5例）
    147: ("penalty_area", ["正常接触"], "correct", "correct"),
    148: ("sfp_vc", ["轻微接触", "暴力行为不成立"], "correct", "correct"),
    149: ("penalty_area", ["主动倒地"], "correct", "correct"),
    150: ("goal_decision", ["争抢位置", "进球有效"], "correct", "correct"),
    151: ("goal_decision", ["轻微接触", "进球有效"], "correct", "none"),
    152: ("penalty_area", ["点球", "拉扯", "规则说明"], "correct", "none"),
    153: ("penalty_area", ["点球重罚", "提前进入"], "wrong", "none"),
    154: ("offside", ["越位误判", "进球有效"], "wrong", "none"),
    155: ("penalty_area", ["误判", "铲球"], "wrong", "none"),
    156: ("penalty_area", ["点球", "铲球"], "wrong", "none"),
    157: ("penalty_area", ["点球", "踩踏", "黄牌"], "wrong", "none"),
    # 期14（标题2例）
    158: ("offside", ["越位位置", "干扰比赛"], "wrong", "none"),
    159: ("sfp_vc", ["红牌", "暴力行为", "击打"], "wrong", "none"),
    160: ("handball", ["意外手球", "自然位置"], "correct", "none"),
    161: ("handball", ["点球", "手臂不自然扩大"], "correct", "none"),
    162: ("sfp_vc", ["黄牌", "手臂", "红牌不成立"], "wrong", "none"),
    163: ("penalty_area", ["正常接触"], "correct", "none"),
    164: ("penalty_area", ["点球", "拉扯", "SPA", "黄牌"], "wrong", "none"),
    # 期15（标题5例）
    165: ("offside", ["越位位置", "干扰对方", "VAR回看错误"], "wrong", "correct"),
    166: ("sfp_vc", ["黄牌", "铲球", "红牌不成立"], "correct", "correct"),
    167: ("offside", ["越位误判"], "wrong", "none"),
    168: ("goal_decision", ["争抢高球", "误判", "提前鸣哨"], "wrong", "none"),
    169: ("goal_decision", ["争抢位置", "进球有效"], "correct", "none"),
    170: ("penalty_area", ["点球", "踢人", "误判"], "wrong", "none"),
    171: ("handball", ["证据不足", "DOGSO不成立"], "pending", "none"),
    172: ("penalty_area", ["正常接触", "误判"], "wrong", "none"),
    # 期16（标题4例；本合集5例——含1例漏判黄牌）
    173: ("penalty_area", ["主动接触"], "correct", "correct"),
    174: ("penalty_area", ["正常接触", "主动倒地"], "correct", "correct"),
    175: ("penalty_area", ["点球", "拉扯"], "correct", "correct"),
    176: ("offside", ["越位误判", "进球有效"], "wrong", "none"),
    177: ("penalty_area", ["点球", "拉扯"], "wrong", "none"),
    178: ("goal_decision", ["正常接触", "进球有效"], "correct", "none"),
    179: ("sfp_vc", ["红牌", "暴力行为", "击打"], "wrong", "none"),
    180: ("sfp_vc", ["红牌不成立", "草率犯规"], "correct", "none"),
    181: ("sfp_vc", ["黄牌", "手臂", "红牌不成立"], "wrong", "none"),
    182: ("sfp_vc", ["黄牌", "铲球", "红牌不成立"], "correct", "none"),
    183: ("handball", ["证据不足"], "pending", "none"),
    184: ("penalty_area", ["守门员", "正常接触"], "correct", "none"),
    185: ("penalty_area", ["点球", "推搡", "SPA", "黄牌"], "wrong", "none"),
    186: ("penalty_area", ["正常接触"], "correct", "none"),
    # 期17（标题口径：无错漏判；本合集0例错漏判，VAR介入错误2例）
    187: ("handball", ["证据不足"], "correct", "correct"),
    188: ("sfp_vc", ["正常接触", "暴力行为不成立"], "correct", "correct"),
    189: ("offside", ["VAR划线", "越位位置获利", "受限触球"], "correct", "correct"),
    190: ("penalty_area", ["正常接触"], "correct", "correct"),
    191: ("offside", ["VAR划线", "越位位置", "干扰比赛"], "correct", "correct"),
    192: ("sfp_vc", ["黄牌", "非体育行为", "红牌不成立"], "correct", "correct"),
    193: ("sfp_vc", ["黄牌", "红牌不成立"], "correct", "correct"),
    194: ("handball", ["意外手球", "进球有效"], "correct", "correct"),
    195: ("penalty_area", ["正常接触", "进球有效"], "correct", "correct"),
    196: ("sfp_vc", ["红牌", "严重犯规", "鞋钉", "VAR介入错误"], "correct", "wrong"),
    197: ("penalty_area", ["正常接触", "VAR介入错误"], "correct", "wrong"),
    198: ("penalty_area", ["点球", "犯规地点"], "correct", "none"),
    199: ("sfp_vc", ["黄牌", "铲球", "红牌不成立"], "correct", "none"),
    200: ("handball", ["证据不足"], "correct", "none"),
    # 期18（标题1例）
    201: ("offside", ["越位位置", "干扰对方不成立"], "correct", "correct"),
    202: ("sfp_vc", ["轻微接触", "暴力行为不成立"], "correct", "correct"),
    203: ("sfp_vc", ["草率犯规", "红牌不成立"], "correct", "correct"),
    204: ("offside", ["越位位置", "干扰对方", "VAR介入正确", "规则说明"], "correct", "correct"),
    205: ("offside", ["越位位置获利", "进球有效"], "wrong", "none"),
    206: ("penalty_area", ["证据不足", "轻微接触"], "correct", "none"),
    # 期19（标题3例；含深圳新鹏城换人程序说明）
    207: ("offside", ["证据不足"], "pending", "none"),
    208: ("sfp_vc", ["红牌", "严重犯规", "蹬踹"], "wrong", "none"),
    209: ("sfp_vc", ["红牌", "暴力行为"], "wrong", "none"),
    210: ("offside", ["证据不足", "越位位置"], "correct", "none"),
    211: ("penalty_area", ["点球", "黄牌不成立"], "wrong", "none"),
    212: ("sfp_vc", ["红牌", "暴力行为", "证据不足"], "wrong", "none"),
    213: ("other_program", ["换人程序", "规则说明"], "correct", "none"),
    # 期20（标题口径：无错漏判）
    214: ("penalty_area", ["正常接触"], "correct", "correct"),
    215: ("penalty_area", ["正常接触"], "correct", "correct"),
    # 期21（标题2例）
    216: ("handball", ["手球", "进球无效"], "wrong", "none"),
    217: ("offside", ["越位误判", "进球有效"], "wrong", "none"),
    218: ("penalty_area", ["正常接触"], "correct", "none"),
    219: ("penalty_area", ["拉扯", "主动倒地"], "correct", "none"),
    220: ("handball", ["意外手球", "自然位置"], "correct", "none"),
    # 期22（标题口径：本轮中超无错漏判；本合集2例为中甲/中乙）
    221: ("handball", ["自然位置"], "correct", "correct"),
    222: ("handball", ["证据不足", "自然位置"], "correct", "correct"),
    223: ("sfp_vc", ["黄牌", "红牌不成立"], "wrong", "correct"),
    224: ("penalty_area", ["点球", "绊摔", "黄牌", "DOGSO降格"], "correct", "none"),
    225: ("penalty_area", ["正常接触", "误判"], "wrong", "none"),
}
