# -*- coding: utf-8 -*-
"""2024赛季判例人工分类表（160条，逐条通读复核）
格式: seq -> (类别, 标签, 裁判判定, VAR判定)
"""

CLS_2024 = {
    1: ("penalty_area", ["VAR介入正确", "进攻发展阶段", "点球"], "correct", "correct"),
    2: ("penalty_area", [], "correct", "none"),
    3: ("penalty_area", ["错判直接任意球"], "wrong", "none"),
    4: ("sfp_vc", ["漏判黄牌", "非体育行为", "挥臂"], "wrong", "none"),
    5: ("goal_decision", ["进球无效", "漏判攻方犯规"], "wrong", "none"),
    6: ("penalty_area", ["证据不足"], "correct", "none"),
    7: ("sfp_vc", ["漏判红牌", "暴力行为", "肘击"], "wrong", "none"),
    8: ("handball", ["错判点球", "证据不足"], "wrong", "none"),
    9: ("goal_decision", ["VAR介入正确", "进球无效", "进攻发展阶段"], "correct", "correct"),
    10: ("sfp_vc", ["红牌", "严重犯规", "VAR介入正确"], "correct", "correct"),
    11: ("penalty_area", ["正常接触"], "correct", "none"),
    12: ("sfp_vc", ["红牌错误", "鲁莽犯规"], "wrong", "correct"),
    13: ("penalty_area", ["正常接触"], "correct", "none"),
    14: ("penalty_area", ["铲球先触球"], "correct", "none"),
    15: ("handball", ["证据不足"], "correct", "none"),
    16: ("dogso", ["红牌", "DOGSO", "守门员"], "correct", "none"),
    17: ("handball", ["点球", "VAR介入正确", "黄牌"], "correct", "correct"),
    18: ("sfp_vc", ["红牌", "严重犯规", "VAR介入错误"], "correct", "wrong"),
    19: ("penalty_area", ["点球错误", "VAR介入错误", "攻方犯规在先"], "wrong", "wrong"),
    20: ("offside", ["越位", "干扰对方队员", "VAR介入错误"], "correct", "wrong"),
    21: ("offside", ["漏判越位", "干扰对方队员", "进球无效"], "wrong", "none"),
    22: ("penalty_area", ["犯规地点在罚球区外"], "correct", "none"),
    23: ("handball", ["自然位置"], "correct", "none"),
    24: ("penalty_area", ["正常接触"], "correct", "none"),
    25: ("sfp_vc", ["红牌错误", "非体育行为"], "wrong", "none"),
    26: ("handball", ["证据不足"], "correct", "none"),
    27: ("handball", ["错判点球", "球未触手臂"], "wrong", "none"),
    28: ("penalty_area", ["正常接触", "主动倒地"], "correct", "none"),
    29: ("sfp_vc", ["黄牌", "红牌不成立", "挥臂"], "correct", "none"),
    30: ("handball", ["点球", "漏判黄牌", "VAR介入正确"], "wrong", "correct"),
    31: ("handball", ["点球", "漏判黄牌", "封堵射门"], "wrong", "none"),
    32: ("goal_decision", ["VAR介入正确", "进球无效", "进攻发展阶段"], "correct", "correct"),
    33: ("goal_decision", ["进攻发展阶段重置", "进球有效"], "correct", "none"),
    34: ("offside", ["证据不足"], "correct", "none"),
    35: ("handball", ["腿部先触球"], "correct", "none"),
    36: ("penalty_area", ["佯装不成立", "夸大接触"], "correct", "none"),
    37: ("penalty_area", ["点球", "草率犯规"], "correct", "none"),
    38: ("handball", ["点球", "VAR介入正确", "黄牌"], "correct", "correct"),
    39: ("freekick_foul", ["漏判黄牌", "鲁莽犯规"], "wrong", "none"),
    40: ("penalty_area", ["漏判点球", "漏判黄牌", "DOGSO", "守门员"], "wrong", "none"),
    41: ("goal_decision", ["进球无效", "漏判攻方犯规", "推人"], "wrong", "none"),
    42: ("handball", ["漏判手球", "错判攻方手球", "手臂不自然扩大"], "wrong", "none"),
    43: ("sfp_vc", ["漏判红牌", "暴力行为", "击打面部"], "wrong", "none"),
    44: ("sfp_vc", ["赛后冲突", "特殊情形", "暴力行为"], "correct", "none"),
    45: ("sfp_vc", ["暴力行为不成立", "意外接触"], "correct", "none"),
    46: ("handball", ["脚封挡后反弹", "手臂合理位置"], "correct", "none"),
    47: ("penalty_area", ["漏判点球", "漏判红牌", "DOGSO", "拉扯"], "wrong", "none"),
    48: ("handball", ["自然位置"], "correct", "none"),
    49: ("handball", ["自然位置"], "correct", "none"),
    50: ("penalty_area", ["封挡触球", "惯性接触"], "correct", "none"),
    51: ("freekick_foul", ["直接任意球", "黄牌", "SPA", "铲球"], "correct", "none"),
    52: ("goal_decision", ["VAR介入正确", "进球有效", "延迟鸣哨", "助理误判"], "correct", "correct"),
    53: ("penalty_area", ["错判点球", "佯装", "主动倒地"], "wrong", "none"),
    54: ("penalty_area", ["错判点球", "漏判红牌", "DOGSO", "犯规地点"], "wrong", "none"),
    55: ("penalty_area", ["错判点球", "漏判红牌", "DOGSO", "犯规地点"], "wrong", "none"),
    56: ("penalty_area", ["自然接触"], "correct", "none"),
    57: ("penalty_area", ["正常接触"], "correct", "none"),
    58: ("goal_decision", ["进球无效", "守门员控球", "VAR未介入错误"], "wrong", "wrong"),
    59: ("dogso", ["红牌", "DOGSO", "直接任意球", "足协杯"], "correct", "none"),
    60: ("handball", ["漏判红牌", "漏判任意球", "手球", "守门员"], "wrong", "none"),
    61: ("handball", ["自然位置", "守门员"], "correct", "none"),
    62: ("penalty_area", ["证据不足"], "correct", "none"),
    63: ("penalty_area", ["铲球触球"], "correct", "none"),
    64: ("sfp_vc", ["红牌", "暴力行为", "无球状态"], "correct", "none"),
    65: ("sfp_vc", ["红牌错误", "黄牌", "非体育行为", "挑衅"], "wrong", "none"),
    66: ("penalty_area", ["守门员", "抢先触球"], "correct", "none"),
    67: ("penalty_area", ["错判点球", "守门员", "先触球"], "wrong", "none"),
    68: ("handball", ["手球", "黄牌", "DOGSO不成立"], "correct", "none"),
    69: ("sfp_vc", ["红牌错误", "黄牌", "非体育行为", "情绪宣泄"], "wrong", "none"),
    70: ("goal_decision", ["漏判进球", "球门线", "判罚难度"], "wrong", "none"),
    71: ("penalty_area", ["正常接触"], "correct", "none"),
    72: ("penalty_area", ["正常对抗"], "correct", "none"),
    73: ("penalty_area", ["错判点球", "佯装", "假摔"], "wrong", "none"),
    74: ("penalty_area", ["单臂接触不犯规"], "correct", "none"),
    75: ("penalty_area", ["证据不足", "铲球"], "correct", "none"),
    76: ("handball", ["证据不足", "点球"], "correct", "none"),
    77: ("sfp_vc", ["暴力行为不成立", "证据不足"], "correct", "none"),
    78: ("handball", ["漏判手球", "进球无效", "其他渠道视频"], "wrong", "none"),
    79: ("goal_decision", ["进球无效", "拉扯犯规", "VAR未介入错误"], "wrong", "wrong"),
    80: ("freekick_foul", ["漏判犯规", "漏判黄牌", "鲁莽犯规", "红牌不成立"], "wrong", "none"),
    81: ("offside", ["漏判越位", "进球无效", "参与争抢"], "wrong", "none"),
    82: ("penalty_area", ["正常接触"], "correct", "none"),
    83: ("penalty_area", ["拉扯不明显"], "correct", "none"),
    84: ("sfp_vc", ["红牌", "暴力行为", "比赛停止时", "助理裁判协助"], "correct", "none"),
    85: ("penalty_area", ["变线导致接触"], "correct", "none"),
    86: ("sfp_vc", ["红牌", "暴力行为", "头撞面部", "比赛停止时"], "correct", "none"),
    87: ("handball", ["漏判手球", "漏判点球", "漏判黄牌", "手臂不自然扩大"], "wrong", "none"),
    88: ("sfp_vc", ["红牌错误", "处罚对象错误", "非体育行为"], "wrong", "none"),
    89: ("penalty_area", ["拉扯不构成犯规"], "correct", "none"),
    90: ("offside", ["漏判越位", "手球", "干扰比赛"], "wrong", "none"),
    91: ("sfp_vc", ["暴力行为不成立", "可接受接触"], "correct", "none"),
    92: ("handball", ["漏判手球", "漏判点球", "手臂张开"], "wrong", "none"),
    93: ("handball", ["球未触手臂"], "correct", "none"),
    94: ("handball", ["手球", "黄牌", "红牌不成立", "守门员"], "correct", "none"),
    95: ("sfp_vc", ["漏判红牌", "严重犯规", "错判危险方式比赛", "恶意踢人"], "wrong", "none"),
    96: ("freekick_foul", ["黄牌", "鲁莽犯规", "铲球"], "correct", "none"),
    97: ("penalty_area", ["漏判点球", "绊摔"], "wrong", "none"),
    98: ("penalty_area", ["错判点球", "拉拽非主因", "主动倒地"], "wrong", "none"),
    99: ("handball", ["错判手球", "错判地点", "手臂合理位置"], "wrong", "none"),
    100: ("penalty_area", ["攻方犯规"], "correct", "none"),
    101: ("penalty_area", ["漏判点球", "草率犯规", "踢人"], "wrong", "none"),
    102: ("sfp_vc", ["漏判红牌", "漏判任意球", "暴力行为", "击打面部"], "wrong", "none"),
    103: ("penalty_area", ["守门员不犯规", "佯装"], "correct", "none"),
    104: ("offside", ["证据不足", "越位"], "correct", "none"),
    105: ("penalty_area", ["铲球触球"], "correct", "none"),
    106: ("penalty_area", ["正常接触", "失去控制"], "correct", "none"),
    107: ("penalty_area", ["点球正确", "黄牌错误", "判例对比"], "wrong", "none"),
    108: ("sfp_vc", ["红牌", "暴力行为", "比赛停止时"], "correct", "none"),
    109: ("penalty_area", ["错判点球", "错判黄牌", "守门员先触球"], "wrong", "none"),
    110: ("penalty_area", ["点球程序", "进球有效", "漏判黄牌"], "wrong", "none"),
    111: ("penalty_area", ["进攻队员主动伸腿"], "correct", "none"),
    112: ("offside", ["VAR介入正确", "3D划线", "越位"], "correct", "correct"),
    113: ("offside", ["VAR未介入正确", "划线选择错误", "赛后复议"], "correct", "correct"),
    114: ("penalty_area", ["点球", "VAR介入正确", "拉扯"], "correct", "correct"),
    115: ("sfp_vc", ["红牌", "暴力行为", "肘击面部", "VAR介入正确"], "correct", "correct"),
    116: ("penalty_area", ["正常接触"], "correct", "none"),
    117: ("penalty_area", ["漏判点球", "VAR未介入错误", "草率犯规"], "wrong", "wrong"),
    118: ("handball", ["点球", "VAR介入正确"], "correct", "correct"),
    119: ("penalty_area", ["正常接触"], "correct", "none"),
    120: ("goal_decision", ["进球有效", "正常接触"], "correct", "none"),
    121: ("offside", ["证据不足", "越位"], "pending", "none"),
    122: ("penalty_area", ["点球", "占据有利位置"], "correct", "none"),
    123: ("penalty_area", ["证据不足", "点球", "守门员"], "correct", "none"),
    124: ("penalty_area", ["守门员", "VAR未介入正确", "足协杯"], "correct", "correct"),
    125: ("penalty_area", ["点球", "拉扯"], "correct", "none"),
    126: ("offside", ["越位获利", "有意触球", "本能触球"], "correct", "none"),
    127: ("freekick_foul", ["漏判犯规", "漏判黄牌", "犯规地点在罚球区外"], "wrong", "none"),
    128: ("handball", ["漏判手球", "漏判点球", "VAR角度限制"], "wrong", "correct"),
    129: ("penalty_area", ["证据不足", "铲球"], "correct", "none"),
    130: ("dogso", ["红牌", "DOGSO", "拉倒"], "correct", "none"),
    131: ("penalty_area", ["正常接触", "守门员"], "correct", "none"),
    132: ("penalty_area", ["漏判点球", "漏判黄牌", "拉扯犯规", "手球无法证明"], "wrong", "none"),
    133: ("handball", ["证据不足"], "correct", "none"),
    134: ("sfp_vc", ["红牌错误", "暴力行为不成立", "无附加动作"], "wrong", "none"),
    135: ("handball", ["证据不足", "手臂非有意"], "correct", "none"),
    136: ("penalty_area", ["点球", "拉扯"], "correct", "none"),
    137: ("handball", ["意外手球", "守门员", "乌龙球"], "correct", "none"),
    138: ("handball", ["漏判手球", "漏判点球", "手臂不自然扩大"], "wrong", "none"),
    139: ("penalty_area", ["错判犯规", "漏判点球", "反判", "草率犯规"], "wrong", "none"),
    140: ("penalty_area", ["维持原判", "VAR介入错误", "轻微接触"], "correct", "wrong"),
    141: ("sfp_vc", ["漏判红牌", "严重犯规", "VAR未介入错误", "危及安全"], "wrong", "wrong"),
    142: ("goal_decision", ["点球程序新规", "VAR介入正确", "提前进入罚球区"], "correct", "correct"),
    143: ("penalty_area", ["漏判点球", "草率犯规", "背后拉拽"], "wrong", "none"),
    144: ("dogso", ["漏判红牌", "DOGSO", "四要素", "抢截犯规"], "wrong", "none"),
    145: ("penalty_area", ["错判犯规", "正常接触", "足协杯"], "wrong", "none"),
    146: ("goal_decision", ["进球有效", "VAR未介入正确", "无法证明触球", "足协杯"], "correct", "correct"),
    147: ("goal_decision", ["进球有效", "VAR介入正确", "球门线"], "correct", "correct"),
    148: ("penalty_area", ["正常接触", "主动倒地"], "correct", "none"),
    149: ("offside", ["证据不足", "越位"], "correct", "none"),
    150: ("penalty_area", ["错判点球", "守门员", "铲球先触球"], "wrong", "none"),
    151: ("sfp_vc", ["漏判红牌", "严重犯规", "踩踏脚踝", "VAR介入正确"], "wrong", "correct"),
    152: ("handball", ["VAR介入正确", "意外手球", "身体反弹"], "correct", "correct"),
    153: ("penalty_area", ["正常接触", "主动倒地", "VAR未介入正确"], "correct", "correct"),
    154: ("handball", ["自然位置", "VAR未介入正确"], "correct", "correct"),
    155: ("handball", ["手球", "点球", "倒地后主动触球"], "correct", "none"),
    156: ("offside", ["漏判越位", "进球无效"], "wrong", "none"),
    157: ("handball", ["自然位置"], "correct", "none"),
    158: ("handball", ["VAR介入错误", "改判错误", "球未触手臂"], "wrong", "wrong"),
    159: ("sfp_vc", ["黄牌", "非体育行为", "守门员控球", "互相冲撞"], "correct", "none"),
    160: ("sfp_vc", ["非体育行为", "比赛恢复方式", "推搡"], "correct", "none"),
}
